const nomes = ['Maria', 'João', 'Eduardo', 'Gabriel', 'Júlia'];

//PRIMEIRO ARGUMENTO DO MÉTODO SPLICE DEVE SER INFORMADO O PRIMEIRO INDICE DO ELEMENTO QUE SERÁ ALTERADO
//NO SEGUNDO ARGUMENTO DEVERÁ SER INFORMADO QUANTOS ELEMENTOS SERÃO REMOVIDOS DO ARRAY
//NO TERCEIRO AGUMENTOS E OS PRÓXIMOS DEVERÃO SER INFORMADOS ELEMENTOS PARA ADICIONAR AO ARRAY
const removidos = nomes.splice(3, 2); //REMOVENDO DOIS ELEMENTOS A PARTIR DO INDICE 3 (Gabriel, POIS O INDICE DO ARRAY INICIA COM 0) 
const adicionar = nomes.splice(3, 2, 'Wesley'); //REMOVENDO DOIS ELEMENTOS A PARTIR DO INDICE 3 E ADICIONANDO UM ELEMENTO NOVO AO ARRAY
console.log(nomes, removidos);